plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    // 必须添加下面这一行
    id 'kotlin-kapt'
}

android {
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.wellcherish.texteditor"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'com.wellcherish.texteditor'
}

dependencies {

    implementation project(":DataSync")
    implementation project(":Base")

    implementation rootProject.ext.deps.coreKtx
    implementation rootProject.ext.deps.appcompat
    implementation rootProject.ext.deps.material
    implementation rootProject.ext.deps.constraintlayout

    implementation rootProject.ext.deps.stdlib
    implementation rootProject.ext.deps.coroutinesCore
    implementation rootProject.ext.deps.coroutinesCoreJvm
    implementation rootProject.ext.deps.coroutinesAndroid

    // Android
    implementation rootProject.ext.deps.activity
    implementation rootProject.ext.deps.fragment
    implementation rootProject.ext.deps.fragmentKtx
    implementation rootProject.ext.deps.legacySupport

    // Room
    implementation rootProject.ext.deps.roomRuntime
    implementation rootProject.ext.deps.roomKtx
    kapt rootProject.ext.deps.roomCompiler
}